version: "3.8"

services:
  postgres:
    container_name: postgres
    image: postgres:17
    volumes:
      - pg-data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: unless-stopped

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    depends_on:
      - zookeeper

  migrate:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    command:
      [
        "-path", "/migrations",
        "-database", "postgres://postgres:1879@postgres:5432/wildberries?sslmode=disable",
        "up"
      ]
    restart: on-failure
    depends_on:
      - postgres

  app:
    container_name: app
    build: .
    volumes:
      - ./logs:/logs
      - ./secrets:/secrets
    env_file:
      - .env
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    depends_on:
      - postgres
      - migrate
    restart: unless-stopped

volumes:
  pg-data:

